services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_PORT: ${API_PORT}
      WEB_ORIGIN: ${WEB_ORIGIN}
      API_PUBLIC_URL: ${API_PUBLIC_URL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_PRIVATE_KEY_BASE64: ${JWT_PRIVATE_KEY_BASE64}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL_DAYS: ${REFRESH_TOKEN_TTL_DAYS}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - dokploy-network
    extra_hosts:
      - "postgres:10.0.1.185"
    expose:
      - "4000"

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      API_INTERNAL_URL: ${API_INTERNAL_URL}
    depends_on:
      - api
    networks:
      - dokploy-network
    expose:
      - "3000"

networks:
  dokploy-network:
    external: true
